"""QRScan tablosu kaldırıldı

Revision ID: d975b3414c5d
Revises: 
Create Date: 2026-01-11 18:34:37.777921

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd975b3414c5d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('qr_scans')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qr_scans',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('qr_code_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('scanned_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['qr_code_id'], ['qr_codes.id'], name=op.f('qr_scans_qr_code_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('qr_scans_pkey'))
    )
    # ### end Alembic commands ###
